Simulation script for the UART is working now

diff --git a/sim/uart/sim_uart b/sim/uart/sim_uart
--- a/sim/uart/sim_uart
+++ b/sim/uart/sim_uart
@@ -21,13 +21,21 @@ if [[ -f "${work}/_info" ]]; then
     rm -vrf "${work}"
 fi
 
+# Exit on errors while we're compiling
+set -e
+
 vlib "${work}"
 vmap work "${work}"
 
-vlog -work "${work}" -sv "${tb_dir}/uart_tb_top.sv"
+vlog -work "${work}" -sv "${tb_dir}/uart_tb_top.v"
 
+vcom -work "${work}" -2008 "${rtl_dir}/baseline/clk_rst.vhd"
 vcom -work "${work}" -2008 "${rtl_dir}/baseline/baud_rate_gen.vhd"
 vcom -work "${work}" -2008 "${rtl_dir}/baseline/uart_rx.vhd"
 vcom -work "${work}" -2008 "${rtl_dir}/baseline/uart_tx.vhd"
 vcom -work "${work}" -2008 "${rtl_dir}/baseline/uart.vhd"
+
+# Done compiling, so turn this back on
+set +e
+
 
